# 기여하신 분 {.unnumbered}

용어 사전에 기여해주신 모든 분들께 감사드립니다. 새로운 기여자와 팀을 찾습니다. 함께 해주실꺼죠?



## Huggingface KREW

[Huggingface KREW](https://pseudo-lab.github.io/huggingface_krew/)는 허깅페이스를 이해하기 다양한 활동을 하고 있으며 허깅페이스 문서를 일관성 있게 번역하기 위해서 용어 사전을 만들고 있습니다.

| 이름   |                                     조직 |           소개|
|:----- |:----------------------------------------|:--------------|
| 서원형 |  Pseudo Lab. Huggingface KREW         |  [Github](https://github.com/wonhyeongseo)/[Linkedin](https://www.linkedin.com/in/wonhseo/)             |
| 손기훈 |  Pseudo Lab. Huggingface KREW         |               |
| 심소현 |  Pseudo Lab. Huggingface KREW         |               |
| 양성모 |  Pseudo Lab. Huggingface KREW         | [Github](https://github.com/gabrielwithappy)/[Linkedin](https://www.linkedin.com/in/%EC%84%B1%EB%AA%A8-%EC%96%91-8a293838/)         |
| 윤현서 |  Pseudo Lab. Huggingface KREW         |        |
| 정우준 | Pseudo Lab. Huggingface KREW        | [Github](https://github.com/jungnerd)       |
| 한나연 | Pseudo Lab. Huggingface KREW         |        |

<br>

## 허깅페이스 Diffuser 번역 프로젝트

| 이름   |                                     조직 |           소개|
|:-----  |:----------------------------------------|:--------------|
| 이홍규 |  Pseudo Lab. Diffuser 프로젝트            |               |
| 박성수 |  Pseudo Lab. Diffuser 프로젝트            |               |
| 이준형 |  Pseudo Lab. Diffuser 프로젝트            |               |
| 윤형석 |  Pseudo Lab. Diffuser 프로젝트            |               |
| 김지환 |  Pseudo Lab. Diffuser 프로젝트            |               |
| 안혜민 |  Pseudo Lab. Diffuser 프로젝트             |               |


## 인과추론팀
가짜연구소 인과추론팀은 한국어 자료가 많지 않은 인과추론을 많은 분들이 쉽게 접하실 수 있도록 기여하고자 합니다!

| 이름   |                                     조직 |           소개|
|:-----  |:----------------------------------------|:--------------|
| 신진수 |  Pseudo Lab. Causal Inference Team      |  [Github](https://github.com/CausalInferenceLab) / [Linkedin](https://www.linkedin.com/in/jinsoo-shin-436060162/) |
